### ISSUE TITLE
errors in shell 

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost/package_check#15]
Running the package checker on my apps, it seems working, but the script is yelling a bit (using current master, on a debian jessie system):

```

./package_check.sh ../ynh-env/apps/ihatemoney_ynh/ -i

The lock file /home/jocelyn/dev/ynh-pkg-check/pcheck.lock is present. Package check would not continue.
Do you want to continue anymore? (y/n) :y
Loads functions from launcher.sh
Loads functions from testing_process.sh
Loads functions from log_extractor.sh
./package_check.sh: ligne 379: /usr/share/yunohost/helpers: Aucun fichier ou dossier de ce type
…
```

**Comment by maniackcrudelis** [comment]
The first thing "is not an error, it's a feature".
Just if you break package check before it ends its job, the lock's still in place.

For the second things, yes it's an error. Because I guess you've installed package check without yunohost.
But, you can forgot this, I think it's just an old thing. Sometime before, you can test a package without lxc, and you have to use yunohost to do that.
I think I can remove this line, I have to try just in case.

**Comment by JocelynDelalande** [comment]
Yes, I was only reporting the second thing, bash error. The lock thing is fine.
