### ISSUE TITLE
Add set -ue to scripts

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost/package_check#17]
Just to avoid continuing a script which got an  error.

**Comment by maniackcrudelis** [comment]
You mean add set -eu in the package check scripts ?

**Comment by JocelynDelalande** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

> You mean add set -eu in the package check scripts ?

Yes

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEECtxJPuKxaTvavr2N6h2HoC+Us1MFAllHB70ACgkQ6h2HoC+U
s1OjzA//cqxGZINNDrQZqM2deZ1x61UThEJCmifPRMZHlCYpiL4eItoryOooViBa
fUsEdsKq12pcaAMkKBrbCtTYqxolDHfIylgROQNWl+hx9YzUIJnv3nqWdFqfVJGp
GMA8MQ4pvaYcQZ7jnAmUCXDTX6C+Qn+6QAo8wtWmB/PI9eI/NjodXU1lub7gErFF
nZQrC0H3D8hAmP/BDXXN9wwytVkcdOuW3AeVuzIVyDJsLNwnbhDWCh5eEeGKQ6Zq
LH5KH0YASUPmBZWz41IfO8HpY2D92jwaAU5KZUeLFBgmtwLQuQTzTcbQMOFQ+BJV
onqybpwXuk9e/dhaJ0i5eAowCwvBzgNsrVpBNhwE0UTYVhb7r73R/oH0S7q77BqF
Ve1MdlHrKqs1cSQXIiyBcqS1KJNIvG328Gi7V+cMJUihHh64WmTFVmTGZQf+0kAJ
tuaQmKRmdyj/wNscUJZhBbKhy3/jjcneATCzwq9McXf1pBHiR+KtsETsdnvsPMxi
5m06N0e3iW4Jhhhx4qFJjFHHIrN3h7gJO9/i3ajlRkJpXv5/DTqN8Eut+EYCfJ36
Dgb6My/ph28o6Kgpk51BDg1JPfBJyM0u6yS9dNO3EmLzqPD5RLrnZDLJWVW4vH1S
nVDQeyD8KIFDTvwDjbRI/fLp9A4FgboBsmeYucamZ3G4BO4lPP0=
=U4iN
-----END PGP SIGNATURE-----

**Comment by maniackcrudelis** [comment]
I've already thought about that.
But, it's more complicated for many conditional test, and more complicated to write the code because you can't deal with unset variable.
And I'm not really sure that's any avantage to do that.
There's no damage if a variable is not set, and no reason for any empty variables.

If a empty variable in the code cause any problem, you should report it and we can try to fix the problem.
