### ISSUE TITLE
Buster support

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost/package_check#69]
Sorry for that noobish question: how do we instantiate an alpha buster LXC container (DISTRIB AND BRANCH setting?). Is it possible to have 2 concurrent containers to alternate stretch/buster tests?
Thanks!

**Comment by maniackcrudelis** [comment]
That's actually quite easy.
You just have to set `DISTRIB=` to buster (for the minimal installation of the container). And `BRANCH=` to the branch of the YunoHost install script, currently [buster-unstable](https://github.com/YunoHost/install_script/tree/buster-unstable).
That's all.

It was possible to have 2 different containers, but this feature has been quite drop since a while.
You can still have a look to https://github.com/YunoHost/CI_package_check/blob/master/auto_build/CI_auto_build.sh
Also, using a different bridge, name and IP is probably enough to run 2 containers. You can change it into the config file.

**Comment by alexAubin** [comment]
Closing because that's fixed
