### ISSUE TITLE
Run package-check via github actions?

### ISSUE THREAD

**Issue by jedie** [YunoHost/package_check#93]
Would be absolute great to run package-check via github actions...

I tried this in https://github.com/YunoHost-Apps/pyinventory_ynh/pull/22 but this doesn’t work, because debian is not available and ubuntu doesn’t work:

![image](https://user-images.githubusercontent.com/71315/102387854-341d9200-3fd1-11eb-9093-7cbb90c59213.png)

See: https://github.com/YunoHost-Apps/pyinventory_ynh/pull/22/checks?check_run_id=1565106520

Crosspost: https://forum.yunohost.org/t/package-check-usage-in-a-virtual-machine/13636

**Comment by alexAubin** [comment]
Hmyeah that requirement for Debian Stretch or Buster was a bit meh ... Next version of package_check should be runnable on many more Linux envs as long as you have LXD installed (much more similar to ynh-dev)

Still I'm not sure how realistic it is to run in github action because you need LXD being properly set up ? And i'm not sure what end Github Actions are using and how much freedom you have within them

But anyway we kind of already have a similar mecanism : if you look at some PR like this one https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/116 you'll find a "build" badge linking to our dev CI, because it automatically triggers jobs for some apps (not sure which ones or how though ...). For now it's running with Jenkins, next version of CI_package_check should run those with the now "classical" yunorunner (same as the regular CI)

**Comment by jedie** [comment]
Alternative is a ci_ynh package for easy self hosted CI ;)

**Comment by kay0u** [comment]
For your information, [this app](https://github.com/YunoHost/yunorunner) packaged in YNH with [this package](https://github.com/YunoHost-Apps/yunorunner_ynh_core) is the front end of our ci-apps.yunohost.org. That's not exactly what you're trying to do, but we could also extend this app instead of rewriting everything from scratch?

It's just an idea, it looks like you know what you're doing :+1 :

**Comment by alexAubin** [comment]
Closing because we can't realistically run big LXC stuff in github actions and it's not practical for various reasons
